### ISSUE TITLE
items: add rich text editor to type description

### ISSUE THREAD

**Issue by vdias38** [meumobi/nfmb-web#118]

**Comment by vdias38** [comment]
[example of ngx-quill and ionic v4](https://github.com/KillerCodeMonkey/ngx-quill-ionic-v4)

## Install
- [ ] `$npm install ngx-quill`
- [ ] include theme stylings of quilljs in `src/global.scss` with `@import` statements
```
@import '~quill/dist/quill.core.css';
@import '~quill/dist/quill.snow.css';

[contenteditable] {
  -webkit-user-select: text;
  user-select: text;
}
```
- [ ] add quilljs to scripts section of angular.json (`architect/build/options`)
```
,
"scripts": [
  "./node_modules/quill/dist/quill.min.js"
]
```
- [ ] import `QuillModule` and add to the imports of ItemsModule NgModule:
```
import { QuillModule } from 'ngx-quill'

@NgModule({
  imports: [
    ...,

    QuillModule.forRoot()
  ],
  ...
})
class ItemsModule { ... }
```
- [ ] Add `<quill-editor></quill-editor>` in item-form template to add a default quill editor

## Global config
- [ ] See [Quill Configuration](https://quilljs.com/docs/configuration/) for a full list of config options
```
    QuillModule.forRoot({
      modules: {
        syntax: true,
        toolbar: [...]
      }
    })
```

## QuillEditorComponent

## QuillViewComponent

**Comment by danconte72** [comment]
-What options we should allow?
I suggest:
Bold, Italic, Underscore, Quote, List and hyperlink only

**Comment by danconte72** [comment]
It's quite annoying edit on mobile. But it works
![image](https://user-images.githubusercontent.com/32454870/74560902-4a3c6b00-4f46-11ea-8176-3f220b7ba2aa.png)

**Comment by danconte72** [comment]
How string is saved on Firestore
![image](https://user-images.githubusercontent.com/32454870/74563686-16644400-4f4c-11ea-85ba-3fca98cad9b2.png)

**Comment by danconte72** [comment]
format on device is not so easy
- I can't select text on iPhone too apply styles 
- I can't add links

**Comment by danconte72** [comment]
to hide toolbar
-[ ] check if platform is ready
-[ ] if isPlatformReady check if is a mobile device
-[ ] if isMobile set quillModules = `{toolbar: false}`
-[ ] if !isMobile set quillModules = `{toolbar: {container: environment.quillOptions.formats}}`
-[ ] update on template `  <quill-editor *ngIf="isPlatformReady" [modules]="quillModules" (...)></quill-editor>`

**Comment by vdias38** [comment]
1. Check if mobile device
> if isPlatformReady check if is a mobile device
what is the test ?

2. Condition to display rich text editor
> <quill-editor *ngIf="isPlatformReady"

Are you sure ? you need to display rich text editor if platformReady or if mobile device ?

What happens if user edit post with rich text on mobile device ?

**Comment by danconte72** [comment]
> What happens if user edit post with rich text on mobile device ?

it shows html code
![image](https://user-images.githubusercontent.com/32454870/74677834-296b5400-5198-11ea-8a0c-5fd4381fbdcc.png)
that is the reason we should keep the editor and only switch if either show or hide the toolbar
> Are you sure ? you need to display rich text editor if platformReady or if mobile device ?

We can only check which platform if isPlatformReady, depending of platform set the toolbar or not
We cannot set toolbar dynamically so we need set it before component render. So only render if isPlatformReady and we know if we need to set toolbar.

> what is the test ? 

this.platform.is('mobile')

**Comment by danconte72** [comment]
![PHOTO-2020-02-14-16-53-37](https://user-images.githubusercontent.com/32454870/74682809-e0ba9780-51a5-11ea-8d70-60dc1434b0c0.jpg)

**Comment by vdias38** [comment]
Example of styles used by gmail on web.
On mobile app gmail allows to edit the wysiwyg view but not to edit styles.

![Re___meumobi_nfmb-web__items__add_rich_text_editor_to_type_description___118__-_victor_dias_meumobi_com_-_MeuMobi_Mail](https://user-images.githubusercontent.com/9011612/74683221-1b312e00-51c0-11ea-809c-ece2f6c691ff.png)

**Comment by danconte72** [comment]
![image](https://user-images.githubusercontent.com/32454870/74686284-cdacc500-51af-11ea-8738-aa2337f3f109.png)

**Comment by danconte72** [comment]
- review font size regression on item-detail 
- remove config from env

**Comment by danconte72** [comment]
we should override css to customize view https://quilljs.com/docs/themes/#customization

**Comment by danconte72** [comment]
devices larger than 1140px
![image](https://user-images.githubusercontent.com/32454870/74863846-543ae100-532d-11ea-85f8-bbfdeb8e374f.png)


devices thinner than 1140px
![image](https://user-images.githubusercontent.com/32454870/74863569-decf1080-532c-11ea-961d-56ebd509e379.png)




mobile view 
![image](https://user-images.githubusercontent.com/32454870/74863518-cbbc4080-532c-11ea-91ab-90d67442e36e.png)
