### ISSUE TITLE
displayName is null on profile when auth by google.com

### ISSUE THREAD

**Issue by vdias38** [meumobi/nfmb-web#12]
observed on c-se profiles

**Comment by danconte72** [comment]
DisplayName returns null when signin By google.com
![image](https://user-images.githubusercontent.com/32454870/69982915-4c308980-1514-11ea-973d-87842bc9fcd0.png)

**Comment by danconte72** [comment]
should uses email as displayName when it null?

**Comment by danconte72** [comment]
We will user local-part from email address when displayName is empty

**Comment by danconte72** [comment]
closed on https://github.com/meumobi/nfmb-master/commit/d3245ccbed395319b4443886751e8f5e979444ff
