### ISSUE TITLE
users cannot scroll categories on web desktop

### ISSUE THREAD

**Issue by danconte72** [meumobi/nfmb-web#121]
### Expected behaviour
Scroll categories on item-list if there are some category hidden

### Steps to reproduce
If user uses Mouse scroll wheel, it rolls the page top-down
If user tries to hold and drag the list, it select the text
Mostly computers have not left-right mouse/trackpad

### Expected responses
- Why it happens
- How to fix it
- How to test

**Comment by vdias38** [comment]
The scroll on items-list (`src/app/items/item-list/item-list.component.html`) use following code

```
    <ion-toolbar>
      <div class="scrollmenu">
        <ion-chip (click)="resetFilters()">
          <ion-label>{{ 'All' | translate }}</ion-label>
        </ion-chip>
        <ion-chip *ngFor="let category of categories" (click)="filterByCategory(category)">
          <ion-label>{{ category }}</ion-label>
        </ion-chip>
      </div>
    </ion-toolbar>
```

And scrollmenu class is define on `src/gloabl.scss`

```
 div.scrollmenu {
  overflow: auto;
  white-space: nowrap;
}

div.scrollmenu::-webkit-scrollbar {
    display: none;  /* Safari and Chrome */
}
```
