### ISSUE TITLE
broken imgs from imageflow due to CORS

### ISSUE THREAD

**Issue by vdias38** [meumobi/nfmb-web#122]
### Expected behaviour
Tell us what should happen

### Actual behaviour
![infomobi](https://user-images.githubusercontent.com/9011612/74384927-3da30000-4dea-11ea-8593-64c0ed095e04.png)

Some imgs appears (DCO, VDI) because these are not from imagelfow.

```
Access to fetch at 'https://imageflow.meumobi.com/nfmb/3FD7?width=1024&scale=both&format=jpg' from origin 'https://web.infomobi.app' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

### Steps to reproduce
I always reproduce, but I've seen it working well before (today) so I don't know why occurs and when starts to fail

### Expected responses
- Why it happens
- How to fix it
- How to test

**Comment by danconte72** [comment]
I've reproduced on web and demo infomobi.app
Did not on localhost, android native (served as localhost), or ios native (served as ionic)

**Comment by danconte72** [comment]
- Https forces CORS
- There was no conf to allow origin on server
- I've update imageflow virtualhost to allow any origin, adding
`Header set Access-Control-Allow-Origin "*"` into VirtualHost tag
- Then  restarted - `$ sudo service apache2 reload`
