### ISSUE TITLE
Update profile model: add devices (array of fcm tokens)

### ISSUE THREAD

**Issue by vdias38** [meumobi/nfmb-web#134]

**Comment by danconte72** [comment]
## To-do
1. update model > item.devices: string[]
2. update fcm services > saveTokenToFirestore(token)
```js
if (!token) { return; }
const currentProfile = await this.authUserService.currentProfile$.pipe(first()).toPromise();
const devices = currentProfile.devices;
if (devices.includes(token)) {return;}
devices.push(token);
return this.itemService.update(currentProfile.id, {devices});
```


ps: as saveTokenToFirestore function will be identical on both web and native service, why not move it to abstract (father) class

**Comment by vdias38** [comment]
Should update `nfmb-master: functions/src/items.ts` to send push to group of devices

**Comment by danconte72** [comment]
i've been working on this branch https://github.com/meumobi/nfmb-web/tree/feat/update-profile-add-devices 
but have faced this error when fcm-services try to access ProfileService
```js
core.js:6014 ERROR Error: Uncaught (in promise): TypeError: this.profileService.update is not a function
TypeError: this.profileService.update is not a function
```
Have I declared all the dependencies correctly?

**Comment by danconte72** [comment]
related to  https://github.com/meumobi/nfmb-master/issues/4

**Comment by danconte72** [comment]
> Have I declared all the dependencies correctly?

provider deps should be in the constructor order
