### ISSUE TITLE
add zoom to img

### ISSUE THREAD

**Issue by vdias38** [meumobi/nfmb-web#15]
img-viewer is not working with ionic 4 https://github.com/Riron/ionic-img-viewer/issues/138 not compatible with angular > 5 neither RXjs > 5
is is not updated since 2017
should look for another lib

An alternative: 
https://github.com/wittlock/ngx-image-zoom#readme -

**Comment by vdias38** [comment]
Some alternatives:
- https://www.npmjs.com/package/ngx-lightbox

**Comment by vdias38** [comment]
I've checked all forks nut none have fixed issues to run on Ionic4, but I've highlighted some interesting updates:

- https://github.com/bipoza/ionic-img-viewer/commit/d895ecfaed8adf3c991be1a433a4e8f9b2c0f40f
- https://github.com/TIME2TRI/ionic-img-viewer/commits/master
- https://github.com/djsanj007/ionic-img-viewer/commit/b3fe58b8f480a1967b980406f0ba46f271b2b70f

**Comment by danconte72** [comment]
should test https://github.com/SimonGolms/ngx-ionic-image-viewer if is iso

**Comment by danconte72** [comment]
I've tested and it worked when the component receives the src without any pipe like
![image](https://user-images.githubusercontent.com/32454870/71832771-623ce700-308a-11ea-9d65-a1cf89fb157f.png)
but for our case we need it to use imageflow 

if we set a pipe like 
![image](https://user-images.githubusercontent.com/32454870/71832842-83053c80-308a-11ea-8889-3f954442df4e.png)

the zoom out image is not accessible 
![image](https://user-images.githubusercontent.com/32454870/71832917-a5975580-308a-11ea-9ab9-8df7e8692068.png)
![image](https://user-images.githubusercontent.com/32454870/71832938-ad56fa00-308a-11ea-9bae-ab962da626b3.png)
but the highresimg works
![image](https://user-images.githubusercontent.com/32454870/71832978-cbbcf580-308a-11ea-81f6-325eb5b0252e.png)

### Conclusion
this component could works for us, but we need to make some changes. Either 'decorate'  imageurl before send it to template or go deep to understand why it not work with pipes.
I didn't find any answer on repo issues

**Comment by danconte72** [comment]
Put this issue and stand-by again

**Comment by danconte72** [comment]
ngx-ionic-image-viewer works only with ion-img and not img
ion-img does not allow do apply css since ionic v4 use shadow dom

**Comment by vdias38** [comment]
> ngx-ionic-image-viewer works only with ion-img and not img
ion-img does not allow do apply css since ionic v4 use shadow dom

then ?...

why we must apply css on img and could not use ion-img?

**Comment by vdias38** [comment]
> Put this issue and stand-by again

?? what does it means ?

**Comment by danconte72** [comment]
> > ngx-ionic-image-viewer works only with ion-img and not img
> > ion-img does not allow do apply css since ionic v4 use shadow dom
> 
> then ?...
> 
> why we must apply css on img and could not use ion-img?
it is necessary user-profile use css on img
![image](https://user-images.githubusercontent.com/32454870/71859141-989b5600-30cc-11ea-826a-35659067529a.png)



> > Put this issue and stand-by again
> 
> ?? what does it means ?
it was put this issue on stand-by.
Once is a nice to have feature, we do not need to implement this issue now.

**Comment by vdias38** [comment]
Could create an own lib or fix the ngx-ionic-image-viewer
The main feature is provided by `ionic-slide` and `swiper-zoom-container` class. It's well explain on [How to Create an Ionic 4 Image Gallery with Zoom](https://www.youtube.com/watch?v=yHDnVarTr2E) Simon Grimm's tutorial.

```ts
<ion-content [forceOverscroll]="false" fullscreen="true">
  <ion-slides [options]="options" #sliderRef>
    <ion-slide>
      <div class="swiper-zoom-container">
        <img alt="alt" [src]="src" height="100vh" />
      </div>
    </ion-slide>
  </ion-slides>
</ion-content>
```

I don't like ngx-ionic-image-viewer because it uses redundant attributes title, text vs alt => inconsistency. And I prefer the simplicity of original plugin `<img src="IMAGE_URL" imageViewer="OTHER_IMAGE_URL" />` instead of ton of attributes.

- [ ] Create new ng project "ngx-ionic-img-viewer"
- [ ] Create img-viewer component (modal)
- [ ] Create [img-viewer directive](https://github.com/SimonGolms/ngx-ionic-image-viewer/commit/63decaf1fb2de0ca76268c4f6b263e30b5af9d0b#diff-3ed0a475a5f019024cb21e5848f92a24)

 ```ts
@Input('imageViewer') src: string;
...
@HostListener('click') onClick() {
    this.viewImage(this.src, this.alt);
  }
async viewImage(src: string, alt: string) {
    const modal = await this.modalController.create({...})
}
```

- [ ] Add `ion-slide` on modal template (see above)
- [ ] Update css of modal
  - [ ] Set dark background
  - [ ] Add close button
  - [ ] Display alt

Should test ASAP with `img` tag, should help to fix `ngx-ionic-image-viewer`

**Comment by vdias38** [comment]
## Setup repo

### Create ionic blank project
```bash
$ ionic start ngx-ionic-img-viewer blank --type=angular
$ cd ngx-ionic-img-viewer/
```
### [Use ng schematics instead of @ionic/angular-toolkit](https://docs.google.com/document/d/1awneyoQ3wXPQXOU0NzkyCv_0ydoYofVDvUciRM4N0jw/edit#heading=h.ehcb89n1ba8p)

### [Generate ng lib](https://docs.google.com/document/d/1awneyoQ3wXPQXOU0NzkyCv_0ydoYofVDvUciRM4N0jw/edit#heading=h.xgq250jtji8a)
$ ng generate library ngx-ionic-img-viewer
