### ISSUE TITLE
missing loading and empty templates on videos page

### ISSUE THREAD

**Issue by vdias38** [meumobi/nfmb-web#21]
Remember to apply good practice and respect consistency.

**Comment by vdias38** [comment]
@danconte72 I've observed a regression raising a critical error

![infomobi](https://user-images.githubusercontent.com/9011612/69691152-116ac380-10c6-11ea-8638-ac2c3f421439.png)

**Comment by danconte72** [comment]
>  I've observed a regression raising a critical error
this is not related with templates. How to get ytChannelId should be updated among with currentProfile
