### ISSUE TITLE
sign-in-with-redirect not working on safari (desktop)

### ISSUE THREAD

**Issue by vdias38** [meumobi/nfmb-web#22]
stick on /auth/sign-in-with-redirect after getting redirect result

**Comment by danconte72** [comment]
Why it happens?
How to fix?
How to test?

**Comment by danconte72** [comment]
I've tested on Safari Desktop 13.0.4 (14608.4.9.1.4) and it worked properly to login with Google, Microsoft, even on a Private Tab.
Although sometimes it take seconds on a blank page  /auth/sign-in-with-redirect
![image](https://user-images.githubusercontent.com/32454870/71846159-a8a13e80-30a8-11ea-8bd3-e386f952cb3f.png)

I've tested on device and got the same result
- long time to load some info
![IMG_0286](https://user-images.githubusercontent.com/32454870/71846888-5eb95800-30aa-11ea-80d0-2eba471858f7.PNG)
- data loaded
![IMG_0287](https://user-images.githubusercontent.com/32454870/71846890-5eb95800-30aa-11ea-9681-4a2da807800d.PNG)
