### ISSUE TITLE
header logo is not centered on iOS

### ISSUE THREAD

**Issue by vdias38** [meumobi/nfmb-web#25]
unexpected right margin

**Comment by danconte72** [comment]
Why it happens?
How to fix?
Hot to test?

**Comment by danconte72** [comment]
image is not centralized into toolbar title
![image](https://user-images.githubusercontent.com/32454870/71741389-8eaff380-2e3d-11ea-83f4-6ca3d8511dda.png)

**Comment by vdias38** [comment]
I don't recommend to add css when behavior is handled by ionic. The response awaited here is why logo is not centered, not how could we fix it. In another word, is is a standard behavior, a Ionic issue, a wrog way we use ionic ... ?

**Comment by vdias38** [comment]
Tested on iPhone SE without patch (commited 7ce08a9) and can't reproduce

**Comment by danconte72** [comment]
I cannot reproduce either, removing the patch. Should remove it definitely

**Comment by vdias38** [comment]
Ok, then i suppose it was fixed on ionic release, can close this issue and remove patch.
I've had a look on ionic changelog but can't find any  mention...
