### ISSUE TITLE
displayName is empty when sign-in by email

### ISSUE THREAD

**Issue by vdias38** [meumobi/nfmb-web#28]
### Actual behaviour
Display Name is filled on invite but when user sign-in it appears empty on profile

### Expected responses
- Why it happens
- How to fix it
- How to test

**Comment by danconte72** [comment]
We will get invite.displayName to set profile.displayName

**Comment by danconte72** [comment]
closed on https://github.com/meumobi/nfmb-master/commit/25c4228e1a23489dff7d29dbb4ef51f3858ab847
