### ISSUE TITLE
wrong organizationId saved on profile when sign-in w/ email

### ISSUE THREAD

**Issue by vdias38** [meumobi/nfmb-web#30]
### Actual behaviour

![nfmb-v4_–_Database_–_Firebase_console](https://user-images.githubusercontent.com/9011612/69974817-e8ab5980-151d-11ea-9188-15a32a3de539.png)

### Steps to reproduce
1. create invite
2. sign-in as invited user
3. should sign-in with orgId = c-se

### Expected responses
- Why it happens
- How to fix it
- How to test

**Comment by danconte72** [comment]
I've created a Invite and logged in 
And profile based on invite had the correct organizationId
![image](https://user-images.githubusercontent.com/32454870/69980724-8c413d80-150f-11ea-8068-93bac1c3984e.png)

**Comment by danconte72** [comment]
There are 3 invites for the same email address 
![image](https://user-images.githubusercontent.com/32454870/69980845-d3c7c980-150f-11ea-8e8f-aa9bc1a8c1bf.png)

**Comment by vdias38** [comment]
I think better to remove invite when user has signed-id

**Comment by danconte72** [comment]
removed invite on 
https://github.com/meumobi/nfmb-master/commit/4cfaffbd760f498f6aab4ce9244ac6b38e72ce02
https://github.com/meumobi/nfmb-master/commit/b6a29a84c9dafc9c6e079370784d6b3544d3bae1

**Comment by danconte72** [comment]
removed daniel and victor invites from collection
