### ISSUE TITLE
Add item.category to filter items

### ISSUE THREAD

**Issue by vdias38** [meumobi/nfmb-web#46]
item.category(: string) should allow to filter items
each item could have a category from organization.categories (: string[])
on item-form should list organization.categories and allow admin to select (drop list) a category
on item-list list organization.categories (horizontal scroll, replace item.tags)

**Comment by danconte72** [comment]
### Changes
- organization model organization.tags > organization.categories
  - update on firestore, there is no tags on organization-form so far
- item model item.tags > item.category
- item service tagFilter > categoryFilter
- item-form ion-chip tags > select category 
- item-list organization.tags > organization.categories

**Comment by danconte72** [comment]
all items need to be associated with a category?
