### ISSUE TITLE
on iOS login page is cropped

### ISSUE THREAD

**Issue by vdias38** [meumobi/nfmb-web#48]
Tested on iPhone 5S, the title is cropped
![Photo from Victor Dias (1)](https://user-images.githubusercontent.com/9011612/70806282-dc8f8980-1db2-11ea-873b-b6e30fd7e5e6.jpg)

**Comment by danconte72** [comment]
Why it happens?
How to fix?
Hot to test?

**Comment by danconte72** [comment]
I could reproduce  on iPhone 8
![IMG_49D8B99B8553-1](https://user-images.githubusercontent.com/32454870/71912411-3ab25100-3154-11ea-83e8-94a39da7b618.jpeg)

**Comment by danconte72** [comment]
## Why it happens
looks like on ios the login form try to centralize itself and sometimes crop the top of
