### ISSUE TITLE
hidenav bar not works well on iOS

### ISSUE THREAD

**Issue by vdias38** [meumobi/nfmb-web#49]
### Expected behaviour
Tell us what should happen

### Actual behaviour
tested on iPhone 5S, on live tab the navbar is always missing, when scroll it appears and disappear "randomly"

### Steps to reproduce
1.
2.
3.

### Expected responses
- Why it happens
- How to fix it
- How to test

**Comment by danconte72** [comment]
remove it

**Comment by vdias38** [comment]
The plugin seems to work well on Android but not on iOS, we observe header flick endless. 
An issue to support iPhone X, XR, XS and XSMax is open on repo but doesn't find anyone to implement.
And should also reduce bundle size of app of 145KB (incl. jquery) of 3.37M total.
