### ISSUE TITLE
push-notification: open a specific page when click on notification

### ISSUE THREAD

**Issue by vdias38** [meumobi/nfmb-web#68]
> You have to add the property “click_ action”: “FCM_PLUGIN_ACTIVITY” to the “notification” object in order to properly use the background method.

https://forum.ionicframework.com/t/go-to-a-specific-page-when-clicking-on-a-notification/123738/14?u=vdias38

**Comment by danconte72** [comment]
https://github.com/angular/angularfire/issues/2299 listen push on web bug

**Comment by danconte72** [comment]
- Created Branch
https://github.com/meumobi/nfmb-web/tree/feat/deeplink-push 
- So far
 - Works on native  - open detail when a push with data.id = id and data.type = module if. items
 - read data is not working on web - https://github.com/angular/angularfire/issues/2299 
 - Should improve to not redirect when app is already open, and ask user action (could be a toast)
 - tested on android device
