### ISSUE TITLE
Firebase Analytics - users numbers seem incorrect

### ISSUE THREAD

**Issue by danconte72** [meumobi/nfmb-web#73]
### Expected behaviour
Correctly track users

### Actual behaviour
![image](https://user-images.githubusercontent.com/32454870/72638281-e4a69000-3941-11ea-97e2-927f7450bf1a.png)
Too many users logged on dashboard

---
For each anonymous tab I've got a different user

### Steps to reproduce
1.
2.
3.

### Expected responses
- Why it happens
- How to fix it
- How to test

**Comment by vdias38** [comment]
can't reproduce
