### ISSUE TITLE
missing default header logo

### ISSUE THREAD

**Issue by vdias38** [meumobi/nfmb-web#81]
### Expected behaviour
Tell us what should happen

### Actual behaviour
![infomobi_and_environment_ts_—_nfmb-web](https://user-images.githubusercontent.com/9011612/73009385-6007b600-3e08-11ea-90ba-f221f63e07f0.png)

### Steps to reproduce
1.
2.
3.

### Expected responses
- Why it happens
- How to fix it
- How to test

**Comment by danconte72** [comment]
![image](https://user-images.githubusercontent.com/32454870/74373101-922e8700-4dba-11ea-8f35-68c4d3170f85.png)
org without log show title as fallback
