### ISSUE TITLE
migrate v3 profiles to v4 miss birthdate

### ISSUE THREAD

**Issue by vdias38** [meumobi/nfmb-web#86]
### Expected behaviour
Tell us what should happen

### Actual behaviour
Following v3 profile `EaK3yc8yLlILdQkdIuLU` has signed in on v4 (`QOA3S2PThQbLvTVIISN5aYSXd162`) but its birthdate is missing 

### Expected responses
- Why it happens
- How to fix it
- How to test

**Comment by danconte72** [comment]
For Katrium
- There were 194 invites 
- Which 92 invites had birthdate set
- 0 profiles with birthdate set

birthdate could be loose on create profile based on invite data (cf)

**Comment by danconte72** [comment]
Birthdate is missing on CF 
```
const profile = {
    displayName: user.displayName,
    email: user.email,
    phoneNumber: user.phoneNumber,
    pictureUrl: picture,
    groups: user.groups,
    type: 'user',
    roles: defaultUserRoles,
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
    modifiedAt: admin.firestore.FieldValue.serverTimestamp(),
    organizationId: organizationId
  }
```

**Comment by danconte72** [comment]
closed on https://github.com/meumobi/nfmb-master/commit/0e6826e87da6283b3f3f2419a914563d36bc985e
