### ISSUE TITLE
hide groups filter for readers

### ISSUE THREAD

**Issue by vdias38** [meumobi/nfmb-web#89]
groups should only be visible by admin and not readers

**Comment by danconte72** [comment]
hide it from profile-list
hide it from profile-detail?

**Comment by danconte72** [comment]
Possible permission names: 
- [can]filter
- [can]editGroups -- could be confused with [can]edit 
- [can]manage

- only show groups for admin and root on usaer/infobox/suatv detail

**Comment by vdias38** [comment]
- [ ] update permissions on `nfmb-data-mgmt/src/lib/profiles/profile.service`
  - replace `viewAll` by `canShowGroups`
- [ ] on profile-list component set `canShowGroups$`
  - `this.canShowGroups$ = this.profileService.currentProfileHasPermissionsTo$('canShowGroups');`
- [ ] on profile-list template add conditional `*ngIf="canShowGroups$ | async"` **on div.scrollMenu** (**DON'T hide search-bar** as done on previous commit)
- [ ] on `profiles/shared/detail/*-detail` component set `canShowGroups$`
- [ ] on `profiles/shared/detail/*-detail` template add conditional `*ngIf="canShowGroups$ | async"` to list groups **on `ion-list`** (**NOT on profileHeader** as done on previous commit because should not be visible on dark primary color)

**Comment by danconte72** [comment]
to be consistent with edit, delete and read, permission should be viewGroups
