### ISSUE TITLE
first|last names are missing on profiles

### ISSUE THREAD

**Issue by vdias38** [meumobi/nfmb-web#92]

**Comment by danconte72** [comment]
## Update models 
### Profile
- Add firstName, lastName
- Update current displayName to 
```
get displayName() {
    return `${firstName} ${lastName}`;
}
```
### Invite
- Add firstName, lastName
- Remove current displayName

## Update CF
### CreateProfile
- profile.firstName = invite.firstName ?  invite.firstName :  invite.displayName;
- profile.lastName = invite.lastName ?  invite.lastName :  '';

## Update Template
### user-form
- Add firstName, lastName
- Remove displayName
### invite-form
- Add firstName, lastName
- Remove displayName
### invite-detail
- Add firstName, lastName
- Remove displayName

**Comment by vdias38** [comment]
missing use case of OAuth authentication when only displayName is available to create profile

**Comment by danconte72** [comment]
- [ ] update models
- [ ] update cf
- [ ] update user-form
- [ ] update invite-form
- [ ] update invite-detail / invite-headline
- [ ] migrate data - Profile
