### ISSUE TITLE
push not received on iOS

### ISSUE THREAD

**Issue by danconte72** [meumobi/nfmb-web#95]
### Expected behaviour
Receive push on iOS device

### Steps to reproduce
1. Send a push to device token 
`f_u_azE927A:APA91bE_VxMyfP8JNJFB-80q3SaTCELvtdZ03nL-U4xsTT8zIsA4GMHD9FJePEWed5Py7qubcdwOa3-xEoOV-7LtXK33nQBZ2zn5e7CplunGj0_aImtu7dEVKMexWznaPJBtrJ3emiz-`

### Data
- User is prompt to allow push
- Device token is created on devices collection

### Expected responses
- Why it happens
- How to fix it
- How to test

**Comment by vdias38** [comment]
The APNS config was missing on Firebase.
Firebase Cloud Messaging can use either an APNs authentication key or APNs certificate to connect with APNs, I've decided to [use APNs authentication key](https://firebase.google.com/docs/cloud-messaging/ios/client#upload_your_apns_authentication_key). Seen on firebase docs [steps to created APNs authentication key](https://firebase.google.com/docs/cloud-messaging/ios/certs)
