### ISSUE TITLE
iOS push use default ionic icon, should set own

### ISSUE THREAD

**Issue by vdias38** [meumobi/nfmb-web#99]

**Comment by vdias38** [comment]
This [commit](https://github.com/meumobi/nfmb-web/commit/8766612c04bcefc0b7dd12aa1d82ea7a1d807176#diff-d664e32d39f301b079052ddc7ab6e4ec) should have fixed it, but not.

Need a review of all resources, icons and splash

**Comment by danconte72** [comment]
## Why it happens
- ios icons where outdated

## How to fix
- rebuild ios icon resources 
`$ ionic cordova resources ios --icon --force`

## How test
- Build a ad hoc version
- Distribute through firebase app distribution
- Sign-in, get Device Token
- Send Push to Device
![image](https://user-images.githubusercontent.com/32454870/73387773-cf215680-42af-11ea-8fac-6530dc1cb0f6.png)
